BEGIN TRANSACTION;
CREATE TABLE 'message' (
	`Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`user_id` TEXT NOT NULL,
  `message` TEXT NOT NULL
);
INSERT INTO 'message' VALUES (1, '12', 'hello');
COMMIT;
